### ISSUE TITLE
Lock remains active when waveguide switch turned off

### ISSUE THREAD

**Issue by ehuang94** [Bridge12Technologies/pyB12MPS#10]
The lock remains on when the waveguide status is turned off by the pyB12MPS package:

Minimal Example:
`mps.wgstatus(1)`
`mps.rfstatus(1)`
`mps.lockstatus(1)`
`mps.wgstatus(0)`

**Comment by tkeller12** [comment]
If we desire this behavior, this will need to be fixed in the MPS Firmware. I'm moving this issue to the issues associated with the MPS Firmware.
