### ISSUE TITLE
Leftover junk on serial port

### ISSUE THREAD

**Issue by thorstenmaly** [Bridge12Technologies/pyB12MPS#7]
After starting the communication with the MPS (e.g. mps.start()) there seems to be some characters left so any command directly after opening the connection will result in an error. Running the command again will give the correct result.

>>> mps.start()
Server starting...
Server started.
MPS initializing...
System Ready
>>> 
>>> 
>>> mps.power()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyB12MPS/pyB12MPS.py", line 382, in power
    return_power = float(return_tenth_dB_power) / 10. # convert to dBm
ValueError: could not convert string to float: 'Synthesizer detected'
>>> 
>>> mps.power()
0.0
>>>

**Comment by tkellerBridge12** [comment]
Added a 0.5 second delay at startup and flushing buffer to clear left over "Synthesizer detected" string.

**Comment by thorstenmaly** [comment]
Resolved in 1.0.8
