### ISSUE TITLE
Typos in Examples of Quick-Start Guide on pyB12MPS page

### ISSUE THREAD

**Issue by ehuang94** [Bridge12Technologies/pyB12MPS#9]
Link: http://pyb12mps.bridge12.com/quick-start.html#communicating-with-the-bridge12-mps

1.  'rxVoltage = mps.rxdiodemv()' should be 'rxVoltage = mps.rxpowermv()'
2. 'print(rxVolrageList)' should be 'print(rxVoltageList)'
3. The whole script is not the same as that from Github

**Comment by tkeller12** [comment]
This issue is now resolved.
